# Generated by Django 3.1.1 on 2020-09-29 18:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upa', '001_upa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upa',
            name='especificacoes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Clinico Geral'), ('item_key2', 'Otorrino'), ('item_key3', 'Infectologia'), ('item_key4', 'Pediatria'), ('item_key5', 'Dermatologia'), ('item_key6', 'Oftamologia'), ('item_key7', 'Neurologia'), ('item_key8', 'Ginecologia'), ('item_key9', 'Geriatria'), ('item_key10', 'Cardiologia'), ('item_key11', 'Neurologia'), ('item_key12', 'Nutrologia')], max_length=122),
        ),
    ]
